#!/usr/bin/env python
"""
consolidate.py — Temporal Pulse Engine (IDE-2)
Generates session, milestone, and epoch knowledge summaries from episodic data.
Activity-based (not calendar-based) to support paused/intermittent projects.
"""
import os
import sys
import json
import glob
import shutil
from datetime import datetime

# Force utf-8
if sys.stdout.encoding and sys.stdout.encoding.lower() != 'utf-8':
    try:
        sys.stdout.reconfigure(encoding='utf-8')
        sys.stderr.reconfigure(encoding='utf-8')
    except AttributeError:
        pass

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, '..', '..'))
WORKSPACE_DIR = os.path.abspath(os.path.join(BASE_DIR, '..'))
EPISODIC_DIR = os.path.join(WORKSPACE_DIR, '.orion', 'episodic')
SESSION_DIR = os.path.join(EPISODIC_DIR, 'sessions')
MILESTONE_DIR = os.path.join(EPISODIC_DIR, 'milestones')
EPOCH_DIR = os.path.join(EPISODIC_DIR, 'epochs')

# Processed tracking directories
SESSION_ARCHIVE = os.path.join(SESSION_DIR, 'processed')
MILESTONE_ARCHIVE = os.path.join(MILESTONE_DIR, 'processed')

SESSION_HISTORY = os.path.join(EPISODIC_DIR, 'session_history.md')
HANDOFF_FILE = os.path.join(WORKSPACE_DIR, '.orion', 'working', 'handoff.md')
LEARNINGS_FILE = os.path.join(BASE_DIR, 'LEARNINGS.md')


def ensure_dirs():
    for d in [SESSION_DIR, MILESTONE_DIR, EPOCH_DIR, SESSION_ARCHIVE, MILESTONE_ARCHIVE]:
        os.makedirs(d, exist_ok=True)


def consolidate_session():
    """Generate a session pulse from session history and handoff."""
    ensure_dirs()
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    output_path = os.path.join(SESSION_DIR, f"session_{timestamp}.md")
    
    # Gather data sources
    session_content = ""
    if os.path.exists(SESSION_HISTORY):
        with open(SESSION_HISTORY, 'r', encoding='utf-8') as f:
            session_content = f.read()
    
    handoff_content = ""
    if os.path.exists(HANDOFF_FILE):
        with open(HANDOFF_FILE, 'r', encoding='utf-8') as f:
            handoff_content = f.read()
    
    learnings_content = ""
    if os.path.exists(LEARNINGS_FILE):
        with open(LEARNINGS_FILE, 'r', encoding='utf-8') as f:
            learnings_content = f.read()
    
    # Extract key patterns from session
    decisions = [l.strip() for l in session_content.split('\n') 
                 if any(kw in l.lower() for kw in ['decided', 'chose', 'picked', 'selected', 'approved'])]
    errors = [l.strip() for l in session_content.split('\n')
              if any(kw in l.lower() for kw in ['error', 'failed', 'crash', 'bug', 'fix'])]
    
    # Generate session pulse
    pulse = f"""# Session Pulse — {timestamp}

## Session Summary
{handoff_content[:500] if handoff_content else '_(no handoff data)_'}

## Decisions Made
{chr(10).join(f'- {d}' for d in decisions[:5]) if decisions else '- _(no explicit decisions detected)_'}

## Errors / Issues
{chr(10).join(f'- {e}' for e in errors[:5]) if errors else '- _(no errors detected)_'}

## Active Learnings
{chr(10).join(learnings_content.split(chr(10))[:10]) if learnings_content else '- _(no learnings yet)_'}

---
_Generated by Temporal Pulse Engine at {datetime.now().isoformat()}_
"""
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(pulse)
    
    print(f"[PULSE] Session pulse generated: {output_path}")
    
    # Check if we should trigger a milestone (e.g. 5 unprocessed sessions)
    unprocessed_sessions = glob.glob(os.path.join(SESSION_DIR, 'session_*.md'))
    if len(unprocessed_sessions) >= 5:
        print(f"[PULSE] 5+ sessions detected. Automatically triggering Milestone Synthesis.")
        consolidate_milestone()
        
    return output_path


def consolidate_milestone():
    """Synthesize unprocessed session pulses into a milestone synthesis."""
    ensure_dirs()
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    output_path = os.path.join(MILESTONE_DIR, f"milestone_{timestamp}.md")
    
    # Find unprocessed session files
    session_files = sorted(glob.glob(os.path.join(SESSION_DIR, 'session_*.md')))
    
    if not session_files:
        print(f"[SKIP] No unprocessed session pulses found.")
        return None
        
    milestone_content = []
    for f_path in session_files:
        fname = os.path.basename(f_path).replace('.md', '')
        with open(f_path, 'r', encoding='utf-8') as f:
            milestone_content.append(f"### {fname}\n{f.read()}")
    
    # Check access hotspots in orion.db
    hotspots = ""
    db_path = os.path.join(WORKSPACE_DIR, '.orion', 'orion.db')
    if os.path.exists(db_path):
        try:
            import sqlite3
            conn = sqlite3.connect(db_path)
            cursor = conn.cursor()
            cursor.execute("PRAGMA table_info(pages)")
            cols = [r[1] for r in cursor.fetchall()]
            if 'access_count' in cols:
                cursor.execute("SELECT path, access_count FROM pages WHERE access_count > 0 ORDER BY access_count DESC LIMIT 5")
                rows = cursor.fetchall()
                if rows:
                    hotspots = "\n".join(f"- {r[0]} ({r[1]} accesses)" for r in rows)
            
            # Check unresolved contradictions
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='contradictions'")
            if cursor.fetchone():
                cursor.execute("SELECT COUNT(*) FROM contradictions WHERE resolution = 'unresolved'")
                unresolved = cursor.fetchone()[0]
                if unresolved:
                    hotspots += f"\n- **{unresolved} unresolved contradictions** pending resolution"
            
            conn.close()
        except Exception as e:
            hotspots = f"_(DB query failed: {e})_"
    
    synthesis = f"""# Milestone Synthesis — {timestamp}

## Sessions Included
{chr(10).join(f'- {os.path.basename(f).replace(".md", "")}' for f in session_files)}

## Knowledge Graph Hotspots
{hotspots if hotspots else '_(no access data yet)_'}

## Combined Session Content

{chr(10).join(milestone_content)}

---
_Generated by Temporal Pulse Engine at {datetime.now().isoformat()}_
"""
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(synthesis)
        
    # Archive processed sessions
    for f_path in session_files:
        shutil.move(f_path, os.path.join(SESSION_ARCHIVE, os.path.basename(f_path)))
    
    print(f"[PULSE] Milestone synthesis generated: {output_path}")
    
    # Check if we should trigger an epoch (e.g. 4 unprocessed milestones)
    unprocessed_milestones = glob.glob(os.path.join(MILESTONE_DIR, 'milestone_*.md'))
    if len(unprocessed_milestones) >= 4:
        print(f"[PULSE] 4+ milestones detected. Automatically triggering Epoch Consolidation.")
        consolidate_epoch()
        
    return output_path


def consolidate_epoch():
    """Compile unprocessed milestone syntheses into an epoch consolidation."""
    ensure_dirs()
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    output_path = os.path.join(EPOCH_DIR, f"epoch_{timestamp}.md")
    
    # Find unprocessed milestone files
    milestone_files = sorted(glob.glob(os.path.join(MILESTONE_DIR, 'milestone_*.md')))
    
    if not milestone_files:
        print(f"[SKIP] No unprocessed milestone syntheses found.")
        return None
    
    epoch_content = []
    for f_path in milestone_files:
        with open(f_path, 'r', encoding='utf-8') as f:
            epoch_content.append(f.read())
    
    consolidation = f"""# Epoch Consolidation — {timestamp}

## Milestones Included
{chr(10).join(f'- {os.path.basename(f)}' for f in milestone_files)}

## Compiled Content

{chr(10).join(epoch_content)}

## Recommended Actions
- [ ] Review patterns for canon promotion (.agents/canons/)
- [ ] Archive session entries older than 90 days
- [ ] Update AGENT_IDENTITY.md with new lessons

---
_Generated by Temporal Pulse Engine at {datetime.now().isoformat()}_
"""
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(consolidation)
        
    # Archive processed milestones
    for f_path in milestone_files:
        shutil.move(f_path, os.path.join(MILESTONE_ARCHIVE, os.path.basename(f_path)))
    
    print(f"[PULSE] Epoch consolidation generated: {output_path}")
    return output_path


def main():
    if len(sys.argv) < 2:
        print("Usage: consolidate.py [session|milestone|epoch]")
        print("  session   — Generate pulse from current session")
        print("  milestone — Synthesize unprocessed sessions (auto-runs at 5 sessions)")
        print("  epoch     — Consolidate unprocessed milestones (auto-runs at 4 milestones)")
        sys.exit(1)
    
    action = sys.argv[1].lower()
    
    if action == 'session' or action == 'daily':
        consolidate_session()
    elif action == 'milestone' or action == 'weekly':
        consolidate_milestone()
    elif action == 'epoch' or action == 'monthly':
        consolidate_epoch()
    else:
        print(f"Unknown action: {action}")
        sys.exit(1)


if __name__ == '__main__':
    main()
