import os
import json
import re
from datetime import datetime

# Configuration
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SOURCE_BASE = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
ROOT_BASE = os.path.abspath(os.path.join(SOURCE_BASE, "..")) # project root
SKILLS_DIR = os.path.join(SOURCE_BASE, "skills")
CATALOG_FILE = os.path.join(SOURCE_BASE, "catalog.json")
WORKSPACE_MAP = os.path.join(SOURCE_BASE, "workspace_map.md")
VERSION_FILE = os.path.join(ROOT_BASE, "VERSION")

def get_version():
    if os.path.exists(VERSION_FILE):
        with open(VERSION_FILE, 'r', encoding='utf-8') as f:
            return f.read().strip()
    return "0.0.0"

def extract_metadata(skill_md_path):
    """
    Extracts name, description, triggers, tags, and tier from SKILL.md Front Matter.
    """
    metadata = {
        "name": os.path.basename(os.path.dirname(skill_md_path)),
        "description": "",
        "triggers": [],
        "tags": [],
        "tier": "Standard" # Default
    }
    
    if not os.path.exists(skill_md_path):
        return metadata

    try:
        with open(skill_md_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
            # Extract YAML-like Front Matter
            front_matter_match = re.search(r'^---\s*\n(.*?)\n---', content, re.DOTALL)
            if front_matter_match:
                front_matter = front_matter_match.group(1)
                
                # Extract description
                desc_match = re.search(r'^description:\s*(.*)', front_matter, re.MULTILINE)
                if desc_match:
                    metadata["description"] = desc_match.group(1).strip()
                
                # Extract triggers
                triggers_match = re.search(r'^triggers:\s*\[(.*?)\]', front_matter, re.MULTILINE)
                if triggers_match:
                    metadata["triggers"] = [t.strip(' "\'') for t in triggers_match.group(1).split(',')]
                
                # Extract tags
                tags_match = re.search(r'^tags:\s*\[(.*?)\]', front_matter, re.MULTILINE)
                if tags_match:
                    metadata["tags"] = [t.strip(' "\'') for t in tags_match.group(1).split(',')]
                
                # Extract tier (Recommended_Tier)
                tier_match = re.search(r'^(?:Recommended_Tier|tier|recommended_tier):\s*(.*)', front_matter, re.MULTILINE)
                if tier_match:
                    metadata["tier"] = tier_match.group(1).strip()
            
            # If description is empty, try to get it from the first # header or first paragraph
            if not metadata["description"]:
                header_match = re.search(r'^#\s+(.*)', content, re.MULTILINE)
                if header_match:
                    metadata["description"] = header_match.group(1).strip()

    except Exception as e:
        print(f"Error reading {skill_md_path}: {e}")
        
    return metadata

def update_workspace_map(skills_list):
    if not os.path.exists(WORKSPACE_MAP):
        return

    # Categorization logic for the map
    categories = {
        "🏛️ Strategy, Architecture & Admin": ["architecture", "admin", "planning", "maintenance"],
        "🏗️ Backend, API & Database": ["backend", "api", "database"],
        "🎨 Data, UI & UX": ["logic", "ui", "ux", "flutter", "debugger"],
        "🛡️ Quality, Security & Audit": ["qa", "testing", "security", "audit"],
        "📈 Marketing & Business (SaaS Growth)": ["business", "marketing"],
        "📚 Knowledge & Optimization": ["utility", "research", "performance", "workflow"]
    }
    
    # Initialize groups
    grouped_skills = {cat: [] for cat in categories}
    grouped_skills["Other"] = []
    
    for skill in skills_list:
        assigned = False
        # Create display string with Tier badge
        tier_label = f"[{skill['tier']}]"
        display_str = f"- `{skill['id']}` {tier_label} — {skill['description'].split('(')[0].strip()}"
        
        for cat, tags in categories.items():
            if any(tag in skill["tags"] for tag in tags):
                grouped_skills[cat].append(display_str)
                assigned = True
                break
        if not assigned:
            grouped_skills["Other"].append(display_str)

    # Build the new Markdown section
    markdown_lines = ["<!-- SKILLS_START -->", "<!-- This section is auto-generated by update_catalog.py. Manual changes will be overwritten. -->"]
    for cat, items in grouped_skills.items():
        if items:
            markdown_lines.append(f"#### {cat}")
            markdown_lines.extend(sorted(items))
            markdown_lines.append("")
    
    markdown_lines.append("<!-- SKILLS_END -->")
    new_skills_content = "\n".join(markdown_lines)

    try:
        with open(WORKSPACE_MAP, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Replace the section between markers
        pattern = r"<!-- SKILLS_START -->.*?<!-- SKILLS_END -->"
        updated_content = re.sub(pattern, new_skills_content, content, flags=re.DOTALL)
        
        with open(WORKSPACE_MAP, 'w', encoding='utf-8') as f:
            f.write(updated_content)
        print(f"Successfully updated {WORKSPACE_MAP} with latest skills.")
    except Exception as e:
        print(f"Error updating workspace_map.md: {e}")

def main():
    if not os.path.exists(SKILLS_DIR):
        print(f"Skills directory {SKILLS_DIR} not found.")
        return

    skills_list = []
    
    # Iterate through all directories in skills/
    skill_dirs = sorted([d for d in os.listdir(SKILLS_DIR) if os.path.isdir(os.path.join(SKILLS_DIR, d))])
    
    for skill_name in skill_dirs:
        skill_path = os.path.join(SKILLS_DIR, skill_name)
        skill_md_path = os.path.join(skill_path, "SKILL.md")
        
        metadata = extract_metadata(skill_md_path)
        
        skill_entry = {
            "id": skill_name,
            "name": metadata["name"],
            "description": metadata["description"],
            "tier": metadata["tier"],
            "path": f".agents/skills/{skill_name}/SKILL.md", # Sanitized relative path
            "triggers": metadata["triggers"],
            "tags": metadata["tags"]
        }
        
        skills_list.append(skill_entry)

    catalog_data = {
        "version": get_version(),
        "generatedAt": datetime.now().isoformat() + "Z",
        "total": len(skills_list),
        "skills": skills_list
    }

    # Write catalog.json
    with open(CATALOG_FILE, 'w', encoding='utf-8') as f:
        json.dump(catalog_data, f, indent=2, ensure_ascii=False)
    
    print(f"Successfully updated catalog.json with {len(skills_list)} skills.")
    
    # Update the human-readable map
    update_workspace_map(skills_list)

if __name__ == "__main__":
    main()